manifest:
  defaults:
    revision: main
  remotes:
    # - name: zmkfirmware
    #  url-base: https://github.com/zmkfirmware
    - name: cormoran
      url-base: https://github.com/cormoran
  projects:
    - name: zmk
      remote: cormoran
      revision: v0.3-branch+dya
      import: app/west.yml

    - name: zmk-module-ble-management
      remote: cormoran
      revision: zmk-v0.3.0.0

    - name: zmk-module-battery-history
      remote: cormoran
      revision: main

    - name: zmk-module-settings-rpc
      remote: cormoran
      revision: main

  self:
    path: config
